// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {controllers} from '../models';

export function Login(arg1:controllers.Credentials):Promise<boolean>;

export function Logout():Promise<void>;
