// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function CreateBarCode(arg1:models.NewBarCode):Promise<void>;

export function DeleteBarCode(arg1:number):Promise<void>;

export function GetBarCodeSrc(arg1:number):Promise<string>;

export function GetBarCodes():Promise<Array<models.BarCode>>;

export function UpdateBarCode(arg1:models.BarCode):Promise<void>;
