// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateBarCode(arg1) {
  return window['go']['controllers']['BarCodes']['CreateBarCode'](arg1);
}

export function DeleteBarCode(arg1) {
  return window['go']['controllers']['BarCodes']['DeleteBarCode'](arg1);
}

export function GetBarCodeSrc(arg1) {
  return window['go']['controllers']['BarCodes']['GetBarCodeSrc'](arg1);
}

export function GetBarCodes() {
  return window['go']['controllers']['BarCodes']['GetBarCodes']();
}

export function UpdateBarCode(arg1) {
  return window['go']['controllers']['BarCodes']['UpdateBarCode'](arg1);
}
