// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetHistory() {
  return window['go']['controllers']['Checkout']['GetHistory']();
}

export function RestoreHistory(arg1) {
  return window['go']['controllers']['Checkout']['RestoreHistory'](arg1);
}

export function SaveCheckout(arg1) {
  return window['go']['controllers']['Checkout']['SaveCheckout'](arg1);
}
