// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function GetHistory():Promise<Array<models.Sale>>;

export function RestoreHistory(arg1:number):Promise<void>;

export function SaveCheckout(arg1:Array<models.ProductGroup>):Promise<void>;
