// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {context} from '../models';

export function GetConfig():Promise<models.ConfigData>;

export function OnStartup(arg1:context.Context):Promise<void>;

export function SaveConfig(arg1:models.ConfigData):Promise<void>;
