// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {controllers} from '../models';
import {models} from '../models';

export function GetDayHistory(arg1:controllers.DataDay):Promise<Array<models.History>>;

export function GetMonthHistory(arg1:controllers.DataMonth):Promise<Array<models.History>>;

export function GetWeekHistory(arg1:controllers.DataWeek):Promise<Array<models.History>>;
