// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDayHistory(arg1) {
  return window['go']['controllers']['History']['GetDayHistory'](arg1);
}

export function GetMonthHistory(arg1) {
  return window['go']['controllers']['History']['GetMonthHistory'](arg1);
}

export function GetWeekHistory(arg1) {
  return window['go']['controllers']['History']['GetWeekHistory'](arg1);
}
