// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function CreateProduct(arg1:models.NewProduct):Promise<void>;

export function DeleteProduct(arg1:number):Promise<void>;

export function GetFilterProducts(arg1:string):Promise<Array<models.Product>>;

export function GetProducts():Promise<Array<models.Product>>;

export function UpdateProduct(arg1:models.DataProduct):Promise<void>;
