// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateProduct(arg1) {
  return window['go']['controllers']['Products']['CreateProduct'](arg1);
}

export function DeleteProduct(arg1) {
  return window['go']['controllers']['Products']['DeleteProduct'](arg1);
}

export function GetFilterProducts(arg1) {
  return window['go']['controllers']['Products']['GetFilterProducts'](arg1);
}

export function GetProducts() {
  return window['go']['controllers']['Products']['GetProducts']();
}

export function UpdateProduct(arg1) {
  return window['go']['controllers']['Products']['UpdateProduct'](arg1);
}
