// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetProfile() {
  return window['go']['controllers']['Profile']['GetProfile']();
}

export function UpdatePassword(arg1) {
  return window['go']['controllers']['Profile']['UpdatePassword'](arg1);
}

export function UpdateProfile(arg1) {
  return window['go']['controllers']['Profile']['UpdateProfile'](arg1);
}
