// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function GetProfile():Promise<models.User>;

export function UpdatePassword(arg1:models.PasswordProfileData):Promise<void>;

export function UpdateProfile(arg1:models.ProfileData):Promise<void>;
