// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteProvider(arg1) {
  return window['go']['controllers']['Providers']['DeleteProvider'](arg1);
}

export function GetProviders() {
  return window['go']['controllers']['Providers']['GetProviders']();
}

export function SaveProvider(arg1) {
  return window['go']['controllers']['Providers']['SaveProvider'](arg1);
}

export function UpdateProvider(arg1) {
  return window['go']['controllers']['Providers']['UpdateProvider'](arg1);
}
