// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function DeleteProvider(arg1:number):Promise<void>;

export function GetProviders():Promise<any>;

export function SaveProvider(arg1:models.NewProvider):Promise<void>;

export function UpdateProvider(arg1:models.Provider):Promise<void>;
