// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateUser(arg1) {
  return window['go']['controllers']['Users']['CreateUser'](arg1);
}

export function DeleteUser(arg1) {
  return window['go']['controllers']['Users']['DeleteUser'](arg1);
}

export function GetUsers() {
  return window['go']['controllers']['Users']['GetUsers']();
}

export function UpdateUser(arg1) {
  return window['go']['controllers']['Users']['UpdateUser'](arg1);
}
