// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function CreateUser(arg1:models.NewUser):Promise<void>;

export function DeleteUser(arg1:number):Promise<void>;

export function GetUsers():Promise<Array<models.User>>;

export function UpdateUser(arg1:models.User):Promise<void>;
