// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: barcodes.proto

package grpcs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BarCode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Tag           string                 `protobuf:"bytes,3,opt,name=tag,proto3" json:"tag,omitempty"`
	Value         string                 `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BarCode) Reset() {
	*x = BarCode{}
	mi := &file_barcodes_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BarCode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BarCode) ProtoMessage() {}

func (x *BarCode) ProtoReflect() protoreflect.Message {
	mi := &file_barcodes_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BarCode.ProtoReflect.Descriptor instead.
func (*BarCode) Descriptor() ([]byte, []int) {
	return file_barcodes_proto_rawDescGZIP(), []int{0}
}

func (x *BarCode) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BarCode) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BarCode) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *BarCode) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type NewBarCode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Tag           string                 `protobuf:"bytes,2,opt,name=tag,proto3" json:"tag,omitempty"`
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewBarCode) Reset() {
	*x = NewBarCode{}
	mi := &file_barcodes_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewBarCode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewBarCode) ProtoMessage() {}

func (x *NewBarCode) ProtoReflect() protoreflect.Message {
	mi := &file_barcodes_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewBarCode.ProtoReflect.Descriptor instead.
func (*NewBarCode) Descriptor() ([]byte, []int) {
	return file_barcodes_proto_rawDescGZIP(), []int{1}
}

func (x *NewBarCode) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NewBarCode) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *NewBarCode) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type BarCodeList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Barcodes      []*BarCode             `protobuf:"bytes,1,rep,name=barcodes,proto3" json:"barcodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BarCodeList) Reset() {
	*x = BarCodeList{}
	mi := &file_barcodes_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BarCodeList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BarCodeList) ProtoMessage() {}

func (x *BarCodeList) ProtoReflect() protoreflect.Message {
	mi := &file_barcodes_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BarCodeList.ProtoReflect.Descriptor instead.
func (*BarCodeList) Descriptor() ([]byte, []int) {
	return file_barcodes_proto_rawDescGZIP(), []int{2}
}

func (x *BarCodeList) GetBarcodes() []*BarCode {
	if x != nil {
		return x.Barcodes
	}
	return nil
}

var File_barcodes_proto protoreflect.FileDescriptor

const file_barcodes_proto_rawDesc = "" +
	"\n" +
	"\x0ebarcodes.proto\x12\x05grpcs\x1a\fcommon.proto\"U\n" +
	"\aBarCode\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03tag\x18\x03 \x01(\tR\x03tag\x12\x14\n" +
	"\x05value\x18\x04 \x01(\tR\x05value\"H\n" +
	"\n" +
	"NewBarCode\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03tag\x18\x02 \x01(\tR\x03tag\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\"9\n" +
	"\vBarCodeList\x12*\n" +
	"\bbarcodes\x18\x01 \x03(\v2\x0e.grpcs.BarCodeR\bbarcodes2\xdc\x01\n" +
	"\bBarCodes\x12)\n" +
	"\x06Create\x12\x11.grpcs.NewBarCode\x1a\f.grpcs.Empty\x12'\n" +
	"\x03Get\x12\x10.grpcs.IdRequest\x1a\x0e.grpcs.BarCode\x12*\n" +
	"\x06GetAll\x12\f.grpcs.Empty\x1a\x12.grpcs.BarCodeList\x12&\n" +
	"\x06Update\x12\x0e.grpcs.BarCode\x1a\f.grpcs.Empty\x12(\n" +
	"\x06Delete\x12\x10.grpcs.IdRequest\x1a\f.grpcs.EmptyB\"Z Miscellaneous/grpcs/protos;grpcsb\x06proto3"

var (
	file_barcodes_proto_rawDescOnce sync.Once
	file_barcodes_proto_rawDescData []byte
)

func file_barcodes_proto_rawDescGZIP() []byte {
	file_barcodes_proto_rawDescOnce.Do(func() {
		file_barcodes_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_barcodes_proto_rawDesc), len(file_barcodes_proto_rawDesc)))
	})
	return file_barcodes_proto_rawDescData
}

var file_barcodes_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_barcodes_proto_goTypes = []any{
	(*BarCode)(nil),     // 0: grpcs.BarCode
	(*NewBarCode)(nil),  // 1: grpcs.NewBarCode
	(*BarCodeList)(nil), // 2: grpcs.BarCodeList
	(*IdRequest)(nil),   // 3: grpcs.IdRequest
	(*Empty)(nil),       // 4: grpcs.Empty
}
var file_barcodes_proto_depIdxs = []int32{
	0, // 0: grpcs.BarCodeList.barcodes:type_name -> grpcs.BarCode
	1, // 1: grpcs.BarCodes.Create:input_type -> grpcs.NewBarCode
	3, // 2: grpcs.BarCodes.Get:input_type -> grpcs.IdRequest
	4, // 3: grpcs.BarCodes.GetAll:input_type -> grpcs.Empty
	0, // 4: grpcs.BarCodes.Update:input_type -> grpcs.BarCode
	3, // 5: grpcs.BarCodes.Delete:input_type -> grpcs.IdRequest
	4, // 6: grpcs.BarCodes.Create:output_type -> grpcs.Empty
	0, // 7: grpcs.BarCodes.Get:output_type -> grpcs.BarCode
	2, // 8: grpcs.BarCodes.GetAll:output_type -> grpcs.BarCodeList
	4, // 9: grpcs.BarCodes.Update:output_type -> grpcs.Empty
	4, // 10: grpcs.BarCodes.Delete:output_type -> grpcs.Empty
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_barcodes_proto_init() }
func file_barcodes_proto_init() {
	if File_barcodes_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_barcodes_proto_rawDesc), len(file_barcodes_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_barcodes_proto_goTypes,
		DependencyIndexes: file_barcodes_proto_depIdxs,
		MessageInfos:      file_barcodes_proto_msgTypes,
	}.Build()
	File_barcodes_proto = out.File
	file_barcodes_proto_goTypes = nil
	file_barcodes_proto_depIdxs = nil
}
