// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: barcodes.proto

package grpcs

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BarCodes_Create_FullMethodName = "/grpcs.BarCodes/Create"
	BarCodes_Get_FullMethodName    = "/grpcs.BarCodes/Get"
	BarCodes_GetAll_FullMethodName = "/grpcs.BarCodes/GetAll"
	BarCodes_Update_FullMethodName = "/grpcs.BarCodes/Update"
	BarCodes_Delete_FullMethodName = "/grpcs.BarCodes/Delete"
)

// BarCodesClient is the client API for BarCodes service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BarCodesClient interface {
	Create(ctx context.Context, in *NewBarCode, opts ...grpc.CallOption) (*Empty, error)
	Get(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*BarCode, error)
	GetAll(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*BarCodeList, error)
	Update(ctx context.Context, in *BarCode, opts ...grpc.CallOption) (*Empty, error)
	Delete(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*Empty, error)
}

type barCodesClient struct {
	cc grpc.ClientConnInterface
}

func NewBarCodesClient(cc grpc.ClientConnInterface) BarCodesClient {
	return &barCodesClient{cc}
}

func (c *barCodesClient) Create(ctx context.Context, in *NewBarCode, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, BarCodes_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *barCodesClient) Get(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*BarCode, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BarCode)
	err := c.cc.Invoke(ctx, BarCodes_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *barCodesClient) GetAll(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*BarCodeList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BarCodeList)
	err := c.cc.Invoke(ctx, BarCodes_GetAll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *barCodesClient) Update(ctx context.Context, in *BarCode, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, BarCodes_Update_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *barCodesClient) Delete(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, BarCodes_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BarCodesServer is the server API for BarCodes service.
// All implementations must embed UnimplementedBarCodesServer
// for forward compatibility.
type BarCodesServer interface {
	Create(context.Context, *NewBarCode) (*Empty, error)
	Get(context.Context, *IdRequest) (*BarCode, error)
	GetAll(context.Context, *Empty) (*BarCodeList, error)
	Update(context.Context, *BarCode) (*Empty, error)
	Delete(context.Context, *IdRequest) (*Empty, error)
	mustEmbedUnimplementedBarCodesServer()
}

// UnimplementedBarCodesServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBarCodesServer struct{}

func (UnimplementedBarCodesServer) Create(context.Context, *NewBarCode) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedBarCodesServer) Get(context.Context, *IdRequest) (*BarCode, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedBarCodesServer) GetAll(context.Context, *Empty) (*BarCodeList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAll not implemented")
}
func (UnimplementedBarCodesServer) Update(context.Context, *BarCode) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedBarCodesServer) Delete(context.Context, *IdRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedBarCodesServer) mustEmbedUnimplementedBarCodesServer() {}
func (UnimplementedBarCodesServer) testEmbeddedByValue()                  {}

// UnsafeBarCodesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BarCodesServer will
// result in compilation errors.
type UnsafeBarCodesServer interface {
	mustEmbedUnimplementedBarCodesServer()
}

func RegisterBarCodesServer(s grpc.ServiceRegistrar, srv BarCodesServer) {
	// If the following call pancis, it indicates UnimplementedBarCodesServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BarCodes_ServiceDesc, srv)
}

func _BarCodes_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewBarCode)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BarCodesServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BarCodes_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BarCodesServer).Create(ctx, req.(*NewBarCode))
	}
	return interceptor(ctx, in, info, handler)
}

func _BarCodes_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BarCodesServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BarCodes_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BarCodesServer).Get(ctx, req.(*IdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BarCodes_GetAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BarCodesServer).GetAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BarCodes_GetAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BarCodesServer).GetAll(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _BarCodes_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BarCode)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BarCodesServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BarCodes_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BarCodesServer).Update(ctx, req.(*BarCode))
	}
	return interceptor(ctx, in, info, handler)
}

func _BarCodes_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BarCodesServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BarCodes_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BarCodesServer).Delete(ctx, req.(*IdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BarCodes_ServiceDesc is the grpc.ServiceDesc for BarCodes service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BarCodes_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpcs.BarCodes",
	HandlerType: (*BarCodesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _BarCodes_Create_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _BarCodes_Get_Handler,
		},
		{
			MethodName: "GetAll",
			Handler:    _BarCodes_GetAll_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _BarCodes_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _BarCodes_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "barcodes.proto",
}
