// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: checkout.proto

package grpcs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NewSale struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       string                 `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Total         float64                `protobuf:"fixed64,3,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewSale) Reset() {
	*x = NewSale{}
	mi := &file_checkout_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewSale) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewSale) ProtoMessage() {}

func (x *NewSale) ProtoReflect() protoreflect.Message {
	mi := &file_checkout_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewSale.ProtoReflect.Descriptor instead.
func (*NewSale) Descriptor() ([]byte, []int) {
	return file_checkout_proto_rawDescGZIP(), []int{0}
}

func (x *NewSale) GetProduct() string {
	if x != nil {
		return x.Product
	}
	return ""
}

func (x *NewSale) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *NewSale) GetTotal() float64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type CreateSaleArgs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sale          *NewSale               `protobuf:"bytes,1,opt,name=sale,proto3" json:"sale,omitempty"`
	IdUser        string                 `protobuf:"bytes,2,opt,name=id_user,json=idUser,proto3" json:"id_user,omitempty"`
	Date          int64                  `protobuf:"varint,3,opt,name=date,proto3" json:"date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSaleArgs) Reset() {
	*x = CreateSaleArgs{}
	mi := &file_checkout_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSaleArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSaleArgs) ProtoMessage() {}

func (x *CreateSaleArgs) ProtoReflect() protoreflect.Message {
	mi := &file_checkout_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSaleArgs.ProtoReflect.Descriptor instead.
func (*CreateSaleArgs) Descriptor() ([]byte, []int) {
	return file_checkout_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSaleArgs) GetSale() *NewSale {
	if x != nil {
		return x.Sale
	}
	return nil
}

func (x *CreateSaleArgs) GetIdUser() string {
	if x != nil {
		return x.IdUser
	}
	return ""
}

func (x *CreateSaleArgs) GetDate() int64 {
	if x != nil {
		return x.Date
	}
	return 0
}

type Sale struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Product       string                 `protobuf:"bytes,2,opt,name=product,proto3" json:"product,omitempty"`
	User          string                 `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	Date          int64                  `protobuf:"varint,4,opt,name=date,proto3" json:"date,omitempty"`
	Count         int32                  `protobuf:"varint,5,opt,name=count,proto3" json:"count,omitempty"`
	Total         float64                `protobuf:"fixed64,6,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sale) Reset() {
	*x = Sale{}
	mi := &file_checkout_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sale) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sale) ProtoMessage() {}

func (x *Sale) ProtoReflect() protoreflect.Message {
	mi := &file_checkout_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sale.ProtoReflect.Descriptor instead.
func (*Sale) Descriptor() ([]byte, []int) {
	return file_checkout_proto_rawDescGZIP(), []int{2}
}

func (x *Sale) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Sale) GetProduct() string {
	if x != nil {
		return x.Product
	}
	return ""
}

func (x *Sale) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *Sale) GetDate() int64 {
	if x != nil {
		return x.Date
	}
	return 0
}

func (x *Sale) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *Sale) GetTotal() float64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type SalesList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sales         []*Sale                `protobuf:"bytes,1,rep,name=sales,proto3" json:"sales,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SalesList) Reset() {
	*x = SalesList{}
	mi := &file_checkout_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SalesList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SalesList) ProtoMessage() {}

func (x *SalesList) ProtoReflect() protoreflect.Message {
	mi := &file_checkout_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SalesList.ProtoReflect.Descriptor instead.
func (*SalesList) Descriptor() ([]byte, []int) {
	return file_checkout_proto_rawDescGZIP(), []int{3}
}

func (x *SalesList) GetSales() []*Sale {
	if x != nil {
		return x.Sales
	}
	return nil
}

var File_checkout_proto protoreflect.FileDescriptor

const file_checkout_proto_rawDesc = "" +
	"\n" +
	"\x0echeckout.proto\x12\x05grpcs\x1a\fcommon.proto\"O\n" +
	"\aNewSale\x12\x18\n" +
	"\aproduct\x18\x01 \x01(\tR\aproduct\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x01R\x05total\"a\n" +
	"\x0eCreateSaleArgs\x12\"\n" +
	"\x04sale\x18\x01 \x01(\v2\x0e.grpcs.NewSaleR\x04sale\x12\x17\n" +
	"\aid_user\x18\x02 \x01(\tR\x06idUser\x12\x12\n" +
	"\x04date\x18\x03 \x01(\x03R\x04date\"\x84\x01\n" +
	"\x04Sale\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aproduct\x18\x02 \x01(\tR\aproduct\x12\x12\n" +
	"\x04user\x18\x03 \x01(\tR\x04user\x12\x12\n" +
	"\x04date\x18\x04 \x01(\x03R\x04date\x12\x14\n" +
	"\x05count\x18\x05 \x01(\x05R\x05count\x12\x14\n" +
	"\x05total\x18\x06 \x01(\x01R\x05total\".\n" +
	"\tSalesList\x12!\n" +
	"\x05sales\x18\x01 \x03(\v2\v.grpcs.SaleR\x05sales2\x9d\x01\n" +
	"\bCheckout\x121\n" +
	"\n" +
	"CreateSale\x12\x15.grpcs.CreateSaleArgs\x1a\f.grpcs.Empty\x120\n" +
	"\n" +
	"GetHistory\x12\x10.grpcs.IdRequest\x1a\x10.grpcs.SalesList\x12,\n" +
	"\n" +
	"DeleteSale\x12\x10.grpcs.IdRequest\x1a\f.grpcs.EmptyB#Z!Miscellaneous/models/protos;grpcsb\x06proto3"

var (
	file_checkout_proto_rawDescOnce sync.Once
	file_checkout_proto_rawDescData []byte
)

func file_checkout_proto_rawDescGZIP() []byte {
	file_checkout_proto_rawDescOnce.Do(func() {
		file_checkout_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_checkout_proto_rawDesc), len(file_checkout_proto_rawDesc)))
	})
	return file_checkout_proto_rawDescData
}

var file_checkout_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_checkout_proto_goTypes = []any{
	(*NewSale)(nil),        // 0: grpcs.NewSale
	(*CreateSaleArgs)(nil), // 1: grpcs.CreateSaleArgs
	(*Sale)(nil),           // 2: grpcs.Sale
	(*SalesList)(nil),      // 3: grpcs.SalesList
	(*IdRequest)(nil),      // 4: grpcs.IdRequest
	(*Empty)(nil),          // 5: grpcs.Empty
}
var file_checkout_proto_depIdxs = []int32{
	0, // 0: grpcs.CreateSaleArgs.sale:type_name -> grpcs.NewSale
	2, // 1: grpcs.SalesList.sales:type_name -> grpcs.Sale
	1, // 2: grpcs.Checkout.CreateSale:input_type -> grpcs.CreateSaleArgs
	4, // 3: grpcs.Checkout.GetHistory:input_type -> grpcs.IdRequest
	4, // 4: grpcs.Checkout.DeleteSale:input_type -> grpcs.IdRequest
	5, // 5: grpcs.Checkout.CreateSale:output_type -> grpcs.Empty
	3, // 6: grpcs.Checkout.GetHistory:output_type -> grpcs.SalesList
	5, // 7: grpcs.Checkout.DeleteSale:output_type -> grpcs.Empty
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_checkout_proto_init() }
func file_checkout_proto_init() {
	if File_checkout_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_checkout_proto_rawDesc), len(file_checkout_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_checkout_proto_goTypes,
		DependencyIndexes: file_checkout_proto_depIdxs,
		MessageInfos:      file_checkout_proto_msgTypes,
	}.Build()
	File_checkout_proto = out.File
	file_checkout_proto_goTypes = nil
	file_checkout_proto_depIdxs = nil
}
