// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: history.proto

package grpcs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HistoryItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Product       string                 `protobuf:"bytes,2,opt,name=product,proto3" json:"product,omitempty"`
	User          string                 `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	Date          int64                  `protobuf:"varint,4,opt,name=date,proto3" json:"date,omitempty"`
	Count         int32                  `protobuf:"varint,5,opt,name=count,proto3" json:"count,omitempty"`
	Total         float32                `protobuf:"fixed32,6,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoryItem) Reset() {
	*x = HistoryItem{}
	mi := &file_history_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoryItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryItem) ProtoMessage() {}

func (x *HistoryItem) ProtoReflect() protoreflect.Message {
	mi := &file_history_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryItem.ProtoReflect.Descriptor instead.
func (*HistoryItem) Descriptor() ([]byte, []int) {
	return file_history_proto_rawDescGZIP(), []int{0}
}

func (x *HistoryItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *HistoryItem) GetProduct() string {
	if x != nil {
		return x.Product
	}
	return ""
}

func (x *HistoryItem) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *HistoryItem) GetDate() int64 {
	if x != nil {
		return x.Date
	}
	return 0
}

func (x *HistoryItem) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *HistoryItem) GetTotal() float32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type SaleResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	IdProduct     string                 `protobuf:"bytes,2,opt,name=id_product,json=idProduct,proto3" json:"id_product,omitempty"`
	IdUser        string                 `protobuf:"bytes,3,opt,name=id_user,json=idUser,proto3" json:"id_user,omitempty"`
	Date          int64                  `protobuf:"varint,4,opt,name=date,proto3" json:"date,omitempty"`
	Count         int32                  `protobuf:"varint,5,opt,name=count,proto3" json:"count,omitempty"`
	Total         float64                `protobuf:"fixed64,6,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaleResult) Reset() {
	*x = SaleResult{}
	mi := &file_history_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaleResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaleResult) ProtoMessage() {}

func (x *SaleResult) ProtoReflect() protoreflect.Message {
	mi := &file_history_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaleResult.ProtoReflect.Descriptor instead.
func (*SaleResult) Descriptor() ([]byte, []int) {
	return file_history_proto_rawDescGZIP(), []int{1}
}

func (x *SaleResult) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SaleResult) GetIdProduct() string {
	if x != nil {
		return x.IdProduct
	}
	return ""
}

func (x *SaleResult) GetIdUser() string {
	if x != nil {
		return x.IdUser
	}
	return ""
}

func (x *SaleResult) GetDate() int64 {
	if x != nil {
		return x.Date
	}
	return 0
}

func (x *SaleResult) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *SaleResult) GetTotal() float64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetByRangeArgs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Start         int64                  `protobuf:"varint,1,opt,name=start,proto3" json:"start,omitempty"`
	End           int64                  `protobuf:"varint,2,opt,name=end,proto3" json:"end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetByRangeArgs) Reset() {
	*x = GetByRangeArgs{}
	mi := &file_history_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetByRangeArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByRangeArgs) ProtoMessage() {}

func (x *GetByRangeArgs) ProtoReflect() protoreflect.Message {
	mi := &file_history_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByRangeArgs.ProtoReflect.Descriptor instead.
func (*GetByRangeArgs) Descriptor() ([]byte, []int) {
	return file_history_proto_rawDescGZIP(), []int{2}
}

func (x *GetByRangeArgs) GetStart() int64 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *GetByRangeArgs) GetEnd() int64 {
	if x != nil {
		return x.End
	}
	return 0
}

type HistoryList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*HistoryItem         `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoryList) Reset() {
	*x = HistoryList{}
	mi := &file_history_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoryList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryList) ProtoMessage() {}

func (x *HistoryList) ProtoReflect() protoreflect.Message {
	mi := &file_history_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryList.ProtoReflect.Descriptor instead.
func (*HistoryList) Descriptor() ([]byte, []int) {
	return file_history_proto_rawDescGZIP(), []int{3}
}

func (x *HistoryList) GetItems() []*HistoryItem {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_history_proto protoreflect.FileDescriptor

const file_history_proto_rawDesc = "" +
	"\n" +
	"\rhistory.proto\x12\x05grpcs\x1a\fcommon.proto\"\x8b\x01\n" +
	"\vHistoryItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aproduct\x18\x02 \x01(\tR\aproduct\x12\x12\n" +
	"\x04user\x18\x03 \x01(\tR\x04user\x12\x12\n" +
	"\x04date\x18\x04 \x01(\x03R\x04date\x12\x14\n" +
	"\x05count\x18\x05 \x01(\x05R\x05count\x12\x14\n" +
	"\x05total\x18\x06 \x01(\x02R\x05total\"\x94\x01\n" +
	"\n" +
	"SaleResult\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"id_product\x18\x02 \x01(\tR\tidProduct\x12\x17\n" +
	"\aid_user\x18\x03 \x01(\tR\x06idUser\x12\x12\n" +
	"\x04date\x18\x04 \x01(\x03R\x04date\x12\x14\n" +
	"\x05count\x18\x05 \x01(\x05R\x05count\x12\x14\n" +
	"\x05total\x18\x06 \x01(\x01R\x05total\"8\n" +
	"\x0eGetByRangeArgs\x12\x14\n" +
	"\x05start\x18\x01 \x01(\x03R\x05start\x12\x10\n" +
	"\x03end\x18\x02 \x01(\x03R\x03end\"7\n" +
	"\vHistoryList\x12(\n" +
	"\x05items\x18\x01 \x03(\v2\x12.grpcs.HistoryItemR\x05items2s\n" +
	"\aHistory\x12/\n" +
	"\bFindByID\x12\x10.grpcs.IdRequest\x1a\x11.grpcs.SaleResult\x127\n" +
	"\n" +
	"GetByRange\x12\x15.grpcs.GetByRangeArgs\x1a\x12.grpcs.HistoryListB#Z!Miscellaneous/models/protos;grpcsb\x06proto3"

var (
	file_history_proto_rawDescOnce sync.Once
	file_history_proto_rawDescData []byte
)

func file_history_proto_rawDescGZIP() []byte {
	file_history_proto_rawDescOnce.Do(func() {
		file_history_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_history_proto_rawDesc), len(file_history_proto_rawDesc)))
	})
	return file_history_proto_rawDescData
}

var file_history_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_history_proto_goTypes = []any{
	(*HistoryItem)(nil),    // 0: grpcs.HistoryItem
	(*SaleResult)(nil),     // 1: grpcs.SaleResult
	(*GetByRangeArgs)(nil), // 2: grpcs.GetByRangeArgs
	(*HistoryList)(nil),    // 3: grpcs.HistoryList
	(*IdRequest)(nil),      // 4: grpcs.IdRequest
}
var file_history_proto_depIdxs = []int32{
	0, // 0: grpcs.HistoryList.items:type_name -> grpcs.HistoryItem
	4, // 1: grpcs.History.FindByID:input_type -> grpcs.IdRequest
	2, // 2: grpcs.History.GetByRange:input_type -> grpcs.GetByRangeArgs
	1, // 3: grpcs.History.FindByID:output_type -> grpcs.SaleResult
	3, // 4: grpcs.History.GetByRange:output_type -> grpcs.HistoryList
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_history_proto_init() }
func file_history_proto_init() {
	if File_history_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_history_proto_rawDesc), len(file_history_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_history_proto_goTypes,
		DependencyIndexes: file_history_proto_depIdxs,
		MessageInfos:      file_history_proto_msgTypes,
	}.Build()
	File_history_proto = out.File
	file_history_proto_goTypes = nil
	file_history_proto_depIdxs = nil
}
