// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: info.proto

package grpcs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInfoRequest) Reset() {
	*x = GetInfoRequest{}
	mi := &file_info_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInfoRequest) ProtoMessage() {}

func (x *GetInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_info_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInfoRequest.ProtoReflect.Descriptor instead.
func (*GetInfoRequest) Descriptor() ([]byte, []int) {
	return file_info_proto_rawDescGZIP(), []int{0}
}

func (x *GetInfoRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetConnectionsCountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int32                  `protobuf:"varint,1,opt,name=Count,proto3" json:"Count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConnectionsCountRequest) Reset() {
	*x = GetConnectionsCountRequest{}
	mi := &file_info_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConnectionsCountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConnectionsCountRequest) ProtoMessage() {}

func (x *GetConnectionsCountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_info_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConnectionsCountRequest.ProtoReflect.Descriptor instead.
func (*GetConnectionsCountRequest) Descriptor() ([]byte, []int) {
	return file_info_proto_rawDescGZIP(), []int{1}
}

func (x *GetConnectionsCountRequest) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_info_proto protoreflect.FileDescriptor

const file_info_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"info.proto\x12\x05grpcs\x1a\fcommon.proto\"$\n" +
	"\x0eGetInfoRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"2\n" +
	"\x1aGetConnectionsCountRequest\x12\x14\n" +
	"\x05Count\x18\x01 \x01(\x05R\x05Count2~\n" +
	"\x04Info\x12.\n" +
	"\aGetName\x12\f.grpcs.Empty\x1a\x15.grpcs.GetInfoRequest\x12F\n" +
	"\x13GetConnectionsCount\x12\f.grpcs.Empty\x1a!.grpcs.GetConnectionsCountRequestB\"Z Miscellaneous/grpcs/protos;grpcsb\x06proto3"

var (
	file_info_proto_rawDescOnce sync.Once
	file_info_proto_rawDescData []byte
)

func file_info_proto_rawDescGZIP() []byte {
	file_info_proto_rawDescOnce.Do(func() {
		file_info_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_info_proto_rawDesc), len(file_info_proto_rawDesc)))
	})
	return file_info_proto_rawDescData
}

var file_info_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_info_proto_goTypes = []any{
	(*GetInfoRequest)(nil),             // 0: grpcs.GetInfoRequest
	(*GetConnectionsCountRequest)(nil), // 1: grpcs.GetConnectionsCountRequest
	(*Empty)(nil),                      // 2: grpcs.Empty
}
var file_info_proto_depIdxs = []int32{
	2, // 0: grpcs.Info.GetName:input_type -> grpcs.Empty
	2, // 1: grpcs.Info.GetConnectionsCount:input_type -> grpcs.Empty
	0, // 2: grpcs.Info.GetName:output_type -> grpcs.GetInfoRequest
	1, // 3: grpcs.Info.GetConnectionsCount:output_type -> grpcs.GetConnectionsCountRequest
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_info_proto_init() }
func file_info_proto_init() {
	if File_info_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_info_proto_rawDesc), len(file_info_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_info_proto_goTypes,
		DependencyIndexes: file_info_proto_depIdxs,
		MessageInfos:      file_info_proto_msgTypes,
	}.Build()
	File_info_proto = out.File
	file_info_proto_goTypes = nil
	file_info_proto_depIdxs = nil
}
