// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: products.proto

package grpcs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Product struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Sku           string                 `protobuf:"bytes,4,opt,name=sku,proto3" json:"sku,omitempty"`
	Price         float64                `protobuf:"fixed64,5,opt,name=price,proto3" json:"price,omitempty"`
	Stock         int32                  `protobuf:"varint,6,opt,name=stock,proto3" json:"stock,omitempty"`
	MinStock      int32                  `protobuf:"varint,7,opt,name=min_stock,json=minStock,proto3" json:"min_stock,omitempty"`
	Provider      *Provider              `protobuf:"bytes,8,opt,name=provider,proto3" json:"provider,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Product) Reset() {
	*x = Product{}
	mi := &file_products_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_products_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_products_proto_rawDescGZIP(), []int{0}
}

func (x *Product) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Product) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Product) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Product) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *Product) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Product) GetStock() int32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *Product) GetMinStock() int32 {
	if x != nil {
		return x.MinStock
	}
	return 0
}

func (x *Product) GetProvider() *Provider {
	if x != nil {
		return x.Provider
	}
	return nil
}

type NewProduct struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Sku           string                 `protobuf:"bytes,3,opt,name=sku,proto3" json:"sku,omitempty"`
	Price         float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	Stock         int32                  `protobuf:"varint,5,opt,name=stock,proto3" json:"stock,omitempty"`
	MinStock      int32                  `protobuf:"varint,6,opt,name=min_stock,json=minStock,proto3" json:"min_stock,omitempty"`
	IdProvider    string                 `protobuf:"bytes,7,opt,name=id_provider,json=idProvider,proto3" json:"id_provider,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewProduct) Reset() {
	*x = NewProduct{}
	mi := &file_products_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewProduct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewProduct) ProtoMessage() {}

func (x *NewProduct) ProtoReflect() protoreflect.Message {
	mi := &file_products_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewProduct.ProtoReflect.Descriptor instead.
func (*NewProduct) Descriptor() ([]byte, []int) {
	return file_products_proto_rawDescGZIP(), []int{1}
}

func (x *NewProduct) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NewProduct) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *NewProduct) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *NewProduct) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *NewProduct) GetStock() int32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *NewProduct) GetMinStock() int32 {
	if x != nil {
		return x.MinStock
	}
	return 0
}

func (x *NewProduct) GetIdProvider() string {
	if x != nil {
		return x.IdProvider
	}
	return ""
}

type DataProduct struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Sku           string                 `protobuf:"bytes,4,opt,name=sku,proto3" json:"sku,omitempty"`
	Price         float64                `protobuf:"fixed64,5,opt,name=price,proto3" json:"price,omitempty"`
	Stock         int32                  `protobuf:"varint,6,opt,name=stock,proto3" json:"stock,omitempty"`
	MinStock      int32                  `protobuf:"varint,7,opt,name=min_stock,json=minStock,proto3" json:"min_stock,omitempty"`
	IdProvider    string                 `protobuf:"bytes,8,opt,name=id_provider,json=idProvider,proto3" json:"id_provider,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataProduct) Reset() {
	*x = DataProduct{}
	mi := &file_products_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataProduct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataProduct) ProtoMessage() {}

func (x *DataProduct) ProtoReflect() protoreflect.Message {
	mi := &file_products_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataProduct.ProtoReflect.Descriptor instead.
func (*DataProduct) Descriptor() ([]byte, []int) {
	return file_products_proto_rawDescGZIP(), []int{2}
}

func (x *DataProduct) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DataProduct) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DataProduct) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *DataProduct) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *DataProduct) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *DataProduct) GetStock() int32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *DataProduct) GetMinStock() int32 {
	if x != nil {
		return x.MinStock
	}
	return 0
}

func (x *DataProduct) GetIdProvider() string {
	if x != nil {
		return x.IdProvider
	}
	return ""
}

type UpdateStockArgs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Stock         int32                  `protobuf:"varint,2,opt,name=stock,proto3" json:"stock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStockArgs) Reset() {
	*x = UpdateStockArgs{}
	mi := &file_products_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStockArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStockArgs) ProtoMessage() {}

func (x *UpdateStockArgs) ProtoReflect() protoreflect.Message {
	mi := &file_products_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStockArgs.ProtoReflect.Descriptor instead.
func (*UpdateStockArgs) Descriptor() ([]byte, []int) {
	return file_products_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateStockArgs) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateStockArgs) GetStock() int32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

type QueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRequest) Reset() {
	*x = QueryRequest{}
	mi := &file_products_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRequest) ProtoMessage() {}

func (x *QueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_products_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRequest.ProtoReflect.Descriptor instead.
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return file_products_proto_rawDescGZIP(), []int{4}
}

func (x *QueryRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type ProductList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*Product             `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductList) Reset() {
	*x = ProductList{}
	mi := &file_products_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductList) ProtoMessage() {}

func (x *ProductList) ProtoReflect() protoreflect.Message {
	mi := &file_products_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductList.ProtoReflect.Descriptor instead.
func (*ProductList) Descriptor() ([]byte, []int) {
	return file_products_proto_rawDescGZIP(), []int{5}
}

func (x *ProductList) GetProducts() []*Product {
	if x != nil {
		return x.Products
	}
	return nil
}

var File_products_proto protoreflect.FileDescriptor

const file_products_proto_rawDesc = "" +
	"\n" +
	"\x0eproducts.proto\x12\x05grpcs\x1a\fcommon.proto\x1a\x0fproviders.proto\"\xd7\x01\n" +
	"\aProduct\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x10\n" +
	"\x03sku\x18\x04 \x01(\tR\x03sku\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x01R\x05price\x12\x14\n" +
	"\x05stock\x18\x06 \x01(\x05R\x05stock\x12\x1b\n" +
	"\tmin_stock\x18\a \x01(\x05R\bminStock\x12+\n" +
	"\bprovider\x18\b \x01(\v2\x0f.grpcs.ProviderR\bprovider\"\xbe\x01\n" +
	"\n" +
	"NewProduct\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x10\n" +
	"\x03sku\x18\x03 \x01(\tR\x03sku\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\x12\x14\n" +
	"\x05stock\x18\x05 \x01(\x05R\x05stock\x12\x1b\n" +
	"\tmin_stock\x18\x06 \x01(\x05R\bminStock\x12\x1f\n" +
	"\vid_provider\x18\a \x01(\tR\n" +
	"idProvider\"\xcf\x01\n" +
	"\vDataProduct\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x10\n" +
	"\x03sku\x18\x04 \x01(\tR\x03sku\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x01R\x05price\x12\x14\n" +
	"\x05stock\x18\x06 \x01(\x05R\x05stock\x12\x1b\n" +
	"\tmin_stock\x18\a \x01(\x05R\bminStock\x12\x1f\n" +
	"\vid_provider\x18\b \x01(\tR\n" +
	"idProvider\"7\n" +
	"\x0fUpdateStockArgs\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05stock\x18\x02 \x01(\x05R\x05stock\"$\n" +
	"\fQueryRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\"9\n" +
	"\vProductList\x12*\n" +
	"\bproducts\x18\x01 \x03(\v2\x0e.grpcs.ProductR\bproducts2\xc6\x02\n" +
	"\bProducts\x12*\n" +
	"\x06GetAll\x12\f.grpcs.Empty\x1a\x12.grpcs.ProductList\x12'\n" +
	"\x03Get\x12\x10.grpcs.IdRequest\x1a\x0e.grpcs.Product\x12/\n" +
	"\x04Find\x12\x13.grpcs.QueryRequest\x1a\x12.grpcs.ProductList\x12)\n" +
	"\x06Create\x12\x11.grpcs.NewProduct\x1a\f.grpcs.Empty\x12*\n" +
	"\x06Update\x12\x12.grpcs.DataProduct\x1a\f.grpcs.Empty\x12(\n" +
	"\x06Delete\x12\x10.grpcs.IdRequest\x1a\f.grpcs.Empty\x123\n" +
	"\vUpdateStock\x12\x16.grpcs.UpdateStockArgs\x1a\f.grpcs.EmptyB\"Z Miscellaneous/grpcs/protos;grpcsb\x06proto3"

var (
	file_products_proto_rawDescOnce sync.Once
	file_products_proto_rawDescData []byte
)

func file_products_proto_rawDescGZIP() []byte {
	file_products_proto_rawDescOnce.Do(func() {
		file_products_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_products_proto_rawDesc), len(file_products_proto_rawDesc)))
	})
	return file_products_proto_rawDescData
}

var file_products_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_products_proto_goTypes = []any{
	(*Product)(nil),         // 0: grpcs.Product
	(*NewProduct)(nil),      // 1: grpcs.NewProduct
	(*DataProduct)(nil),     // 2: grpcs.DataProduct
	(*UpdateStockArgs)(nil), // 3: grpcs.UpdateStockArgs
	(*QueryRequest)(nil),    // 4: grpcs.QueryRequest
	(*ProductList)(nil),     // 5: grpcs.ProductList
	(*Provider)(nil),        // 6: grpcs.Provider
	(*Empty)(nil),           // 7: grpcs.Empty
	(*IdRequest)(nil),       // 8: grpcs.IdRequest
}
var file_products_proto_depIdxs = []int32{
	6, // 0: grpcs.Product.provider:type_name -> grpcs.Provider
	0, // 1: grpcs.ProductList.products:type_name -> grpcs.Product
	7, // 2: grpcs.Products.GetAll:input_type -> grpcs.Empty
	8, // 3: grpcs.Products.Get:input_type -> grpcs.IdRequest
	4, // 4: grpcs.Products.Find:input_type -> grpcs.QueryRequest
	1, // 5: grpcs.Products.Create:input_type -> grpcs.NewProduct
	2, // 6: grpcs.Products.Update:input_type -> grpcs.DataProduct
	8, // 7: grpcs.Products.Delete:input_type -> grpcs.IdRequest
	3, // 8: grpcs.Products.UpdateStock:input_type -> grpcs.UpdateStockArgs
	5, // 9: grpcs.Products.GetAll:output_type -> grpcs.ProductList
	0, // 10: grpcs.Products.Get:output_type -> grpcs.Product
	5, // 11: grpcs.Products.Find:output_type -> grpcs.ProductList
	7, // 12: grpcs.Products.Create:output_type -> grpcs.Empty
	7, // 13: grpcs.Products.Update:output_type -> grpcs.Empty
	7, // 14: grpcs.Products.Delete:output_type -> grpcs.Empty
	7, // 15: grpcs.Products.UpdateStock:output_type -> grpcs.Empty
	9, // [9:16] is the sub-list for method output_type
	2, // [2:9] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_products_proto_init() }
func file_products_proto_init() {
	if File_products_proto != nil {
		return
	}
	file_common_proto_init()
	file_providers_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_products_proto_rawDesc), len(file_products_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_products_proto_goTypes,
		DependencyIndexes: file_products_proto_depIdxs,
		MessageInfos:      file_products_proto_msgTypes,
	}.Build()
	File_products_proto = out.File
	file_products_proto_goTypes = nil
	file_products_proto_depIdxs = nil
}
