// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: profile.proto

package grpcs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProfileData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserName      string                 `protobuf:"bytes,1,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	FullName      string                 `protobuf:"bytes,2,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProfileData) Reset() {
	*x = ProfileData{}
	mi := &file_profile_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfileData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileData) ProtoMessage() {}

func (x *ProfileData) ProtoReflect() protoreflect.Message {
	mi := &file_profile_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfileData.ProtoReflect.Descriptor instead.
func (*ProfileData) Descriptor() ([]byte, []int) {
	return file_profile_proto_rawDescGZIP(), []int{0}
}

func (x *ProfileData) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *ProfileData) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

type UpdateProfileArgs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *ProfileData           `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProfileArgs) Reset() {
	*x = UpdateProfileArgs{}
	mi := &file_profile_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileArgs) ProtoMessage() {}

func (x *UpdateProfileArgs) ProtoReflect() protoreflect.Message {
	mi := &file_profile_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileArgs.ProtoReflect.Descriptor instead.
func (*UpdateProfileArgs) Descriptor() ([]byte, []int) {
	return file_profile_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateProfileArgs) GetData() *ProfileData {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *UpdateProfileArgs) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UpdatePasswordArgs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Password      string                 `protobuf:"bytes,1,opt,name=password,proto3" json:"password,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePasswordArgs) Reset() {
	*x = UpdatePasswordArgs{}
	mi := &file_profile_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePasswordArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePasswordArgs) ProtoMessage() {}

func (x *UpdatePasswordArgs) ProtoReflect() protoreflect.Message {
	mi := &file_profile_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePasswordArgs.ProtoReflect.Descriptor instead.
func (*UpdatePasswordArgs) Descriptor() ([]byte, []int) {
	return file_profile_proto_rawDescGZIP(), []int{2}
}

func (x *UpdatePasswordArgs) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *UpdatePasswordArgs) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_profile_proto protoreflect.FileDescriptor

const file_profile_proto_rawDesc = "" +
	"\n" +
	"\rprofile.proto\x12\x05grpcs\x1a\fcommon.proto\"G\n" +
	"\vProfileData\x12\x1b\n" +
	"\tuser_name\x18\x01 \x01(\tR\buserName\x12\x1b\n" +
	"\tfull_name\x18\x02 \x01(\tR\bfullName\"K\n" +
	"\x11UpdateProfileArgs\x12&\n" +
	"\x04data\x18\x01 \x01(\v2\x12.grpcs.ProfileDataR\x04data\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"@\n" +
	"\x12UpdatePasswordArgs\x12\x1a\n" +
	"\bpassword\x18\x01 \x01(\tR\bpassword\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id2}\n" +
	"\aProfile\x127\n" +
	"\rUpdateProfile\x12\x18.grpcs.UpdateProfileArgs\x1a\f.grpcs.Empty\x129\n" +
	"\x0eUpdatePassword\x12\x19.grpcs.UpdatePasswordArgs\x1a\f.grpcs.EmptyB\"Z Miscellaneous/grpcs/protos;grpcsb\x06proto3"

var (
	file_profile_proto_rawDescOnce sync.Once
	file_profile_proto_rawDescData []byte
)

func file_profile_proto_rawDescGZIP() []byte {
	file_profile_proto_rawDescOnce.Do(func() {
		file_profile_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_profile_proto_rawDesc), len(file_profile_proto_rawDesc)))
	})
	return file_profile_proto_rawDescData
}

var file_profile_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_profile_proto_goTypes = []any{
	(*ProfileData)(nil),        // 0: grpcs.ProfileData
	(*UpdateProfileArgs)(nil),  // 1: grpcs.UpdateProfileArgs
	(*UpdatePasswordArgs)(nil), // 2: grpcs.UpdatePasswordArgs
	(*Empty)(nil),              // 3: grpcs.Empty
}
var file_profile_proto_depIdxs = []int32{
	0, // 0: grpcs.UpdateProfileArgs.data:type_name -> grpcs.ProfileData
	1, // 1: grpcs.Profile.UpdateProfile:input_type -> grpcs.UpdateProfileArgs
	2, // 2: grpcs.Profile.UpdatePassword:input_type -> grpcs.UpdatePasswordArgs
	3, // 3: grpcs.Profile.UpdateProfile:output_type -> grpcs.Empty
	3, // 4: grpcs.Profile.UpdatePassword:output_type -> grpcs.Empty
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_profile_proto_init() }
func file_profile_proto_init() {
	if File_profile_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_profile_proto_rawDesc), len(file_profile_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_profile_proto_goTypes,
		DependencyIndexes: file_profile_proto_depIdxs,
		MessageInfos:      file_profile_proto_msgTypes,
	}.Build()
	File_profile_proto = out.File
	file_profile_proto_goTypes = nil
	file_profile_proto_depIdxs = nil
}
