// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: providers.proto

package grpcs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Provider struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Phone         string                 `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Provider) Reset() {
	*x = Provider{}
	mi := &file_providers_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Provider) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Provider) ProtoMessage() {}

func (x *Provider) ProtoReflect() protoreflect.Message {
	mi := &file_providers_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Provider.ProtoReflect.Descriptor instead.
func (*Provider) Descriptor() ([]byte, []int) {
	return file_providers_proto_rawDescGZIP(), []int{0}
}

func (x *Provider) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Provider) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Provider) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

type NewProvider struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Phone         string                 `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewProvider) Reset() {
	*x = NewProvider{}
	mi := &file_providers_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewProvider) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewProvider) ProtoMessage() {}

func (x *NewProvider) ProtoReflect() protoreflect.Message {
	mi := &file_providers_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewProvider.ProtoReflect.Descriptor instead.
func (*NewProvider) Descriptor() ([]byte, []int) {
	return file_providers_proto_rawDescGZIP(), []int{1}
}

func (x *NewProvider) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NewProvider) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

type ProviderList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Providers     []*Provider            `protobuf:"bytes,1,rep,name=providers,proto3" json:"providers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProviderList) Reset() {
	*x = ProviderList{}
	mi := &file_providers_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderList) ProtoMessage() {}

func (x *ProviderList) ProtoReflect() protoreflect.Message {
	mi := &file_providers_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderList.ProtoReflect.Descriptor instead.
func (*ProviderList) Descriptor() ([]byte, []int) {
	return file_providers_proto_rawDescGZIP(), []int{2}
}

func (x *ProviderList) GetProviders() []*Provider {
	if x != nil {
		return x.Providers
	}
	return nil
}

var File_providers_proto protoreflect.FileDescriptor

const file_providers_proto_rawDesc = "" +
	"\n" +
	"\x0fproviders.proto\x12\x05grpcs\x1a\fcommon.proto\"D\n" +
	"\bProvider\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05phone\x18\x03 \x01(\tR\x05phone\"7\n" +
	"\vNewProvider\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05phone\x18\x02 \x01(\tR\x05phone\"=\n" +
	"\fProviderList\x12-\n" +
	"\tproviders\x18\x01 \x03(\v2\x0f.grpcs.ProviderR\tproviders2\xe1\x01\n" +
	"\tProviders\x12+\n" +
	"\x06GetAll\x12\f.grpcs.Empty\x1a\x13.grpcs.ProviderList\x12(\n" +
	"\x03Get\x12\x10.grpcs.IdRequest\x1a\x0f.grpcs.Provider\x12*\n" +
	"\x06Create\x12\x12.grpcs.NewProvider\x1a\f.grpcs.Empty\x12'\n" +
	"\x06Update\x12\x0f.grpcs.Provider\x1a\f.grpcs.Empty\x12(\n" +
	"\x06Delete\x12\x10.grpcs.IdRequest\x1a\f.grpcs.EmptyB#Z!Miscellaneous/models/protos;grpcsb\x06proto3"

var (
	file_providers_proto_rawDescOnce sync.Once
	file_providers_proto_rawDescData []byte
)

func file_providers_proto_rawDescGZIP() []byte {
	file_providers_proto_rawDescOnce.Do(func() {
		file_providers_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_providers_proto_rawDesc), len(file_providers_proto_rawDesc)))
	})
	return file_providers_proto_rawDescData
}

var file_providers_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_providers_proto_goTypes = []any{
	(*Provider)(nil),     // 0: grpcs.Provider
	(*NewProvider)(nil),  // 1: grpcs.NewProvider
	(*ProviderList)(nil), // 2: grpcs.ProviderList
	(*Empty)(nil),        // 3: grpcs.Empty
	(*IdRequest)(nil),    // 4: grpcs.IdRequest
}
var file_providers_proto_depIdxs = []int32{
	0, // 0: grpcs.ProviderList.providers:type_name -> grpcs.Provider
	3, // 1: grpcs.Providers.GetAll:input_type -> grpcs.Empty
	4, // 2: grpcs.Providers.Get:input_type -> grpcs.IdRequest
	1, // 3: grpcs.Providers.Create:input_type -> grpcs.NewProvider
	0, // 4: grpcs.Providers.Update:input_type -> grpcs.Provider
	4, // 5: grpcs.Providers.Delete:input_type -> grpcs.IdRequest
	2, // 6: grpcs.Providers.GetAll:output_type -> grpcs.ProviderList
	0, // 7: grpcs.Providers.Get:output_type -> grpcs.Provider
	3, // 8: grpcs.Providers.Create:output_type -> grpcs.Empty
	3, // 9: grpcs.Providers.Update:output_type -> grpcs.Empty
	3, // 10: grpcs.Providers.Delete:output_type -> grpcs.Empty
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_providers_proto_init() }
func file_providers_proto_init() {
	if File_providers_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_providers_proto_rawDesc), len(file_providers_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_providers_proto_goTypes,
		DependencyIndexes: file_providers_proto_depIdxs,
		MessageInfos:      file_providers_proto_msgTypes,
	}.Build()
	File_providers_proto = out.File
	file_providers_proto_goTypes = nil
	file_providers_proto_depIdxs = nil
}
