// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: providers.proto

package grpcs

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Providers_GetAll_FullMethodName = "/grpcs.Providers/GetAll"
	Providers_Get_FullMethodName    = "/grpcs.Providers/Get"
	Providers_Create_FullMethodName = "/grpcs.Providers/Create"
	Providers_Update_FullMethodName = "/grpcs.Providers/Update"
	Providers_Delete_FullMethodName = "/grpcs.Providers/Delete"
)

// ProvidersClient is the client API for Providers service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProvidersClient interface {
	GetAll(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ProviderList, error)
	Get(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*Provider, error)
	Create(ctx context.Context, in *NewProvider, opts ...grpc.CallOption) (*Empty, error)
	Update(ctx context.Context, in *Provider, opts ...grpc.CallOption) (*Empty, error)
	Delete(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*Empty, error)
}

type providersClient struct {
	cc grpc.ClientConnInterface
}

func NewProvidersClient(cc grpc.ClientConnInterface) ProvidersClient {
	return &providersClient{cc}
}

func (c *providersClient) GetAll(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ProviderList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProviderList)
	err := c.cc.Invoke(ctx, Providers_GetAll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providersClient) Get(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*Provider, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Provider)
	err := c.cc.Invoke(ctx, Providers_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providersClient) Create(ctx context.Context, in *NewProvider, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Providers_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providersClient) Update(ctx context.Context, in *Provider, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Providers_Update_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providersClient) Delete(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Providers_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProvidersServer is the server API for Providers service.
// All implementations must embed UnimplementedProvidersServer
// for forward compatibility.
type ProvidersServer interface {
	GetAll(context.Context, *Empty) (*ProviderList, error)
	Get(context.Context, *IdRequest) (*Provider, error)
	Create(context.Context, *NewProvider) (*Empty, error)
	Update(context.Context, *Provider) (*Empty, error)
	Delete(context.Context, *IdRequest) (*Empty, error)
	mustEmbedUnimplementedProvidersServer()
}

// UnimplementedProvidersServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProvidersServer struct{}

func (UnimplementedProvidersServer) GetAll(context.Context, *Empty) (*ProviderList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAll not implemented")
}
func (UnimplementedProvidersServer) Get(context.Context, *IdRequest) (*Provider, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedProvidersServer) Create(context.Context, *NewProvider) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedProvidersServer) Update(context.Context, *Provider) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedProvidersServer) Delete(context.Context, *IdRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedProvidersServer) mustEmbedUnimplementedProvidersServer() {}
func (UnimplementedProvidersServer) testEmbeddedByValue()                   {}

// UnsafeProvidersServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProvidersServer will
// result in compilation errors.
type UnsafeProvidersServer interface {
	mustEmbedUnimplementedProvidersServer()
}

func RegisterProvidersServer(s grpc.ServiceRegistrar, srv ProvidersServer) {
	// If the following call pancis, it indicates UnimplementedProvidersServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Providers_ServiceDesc, srv)
}

func _Providers_GetAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProvidersServer).GetAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Providers_GetAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProvidersServer).GetAll(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Providers_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProvidersServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Providers_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProvidersServer).Get(ctx, req.(*IdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Providers_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewProvider)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProvidersServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Providers_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProvidersServer).Create(ctx, req.(*NewProvider))
	}
	return interceptor(ctx, in, info, handler)
}

func _Providers_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Provider)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProvidersServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Providers_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProvidersServer).Update(ctx, req.(*Provider))
	}
	return interceptor(ctx, in, info, handler)
}

func _Providers_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProvidersServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Providers_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProvidersServer).Delete(ctx, req.(*IdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Providers_ServiceDesc is the grpc.ServiceDesc for Providers service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Providers_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpcs.Providers",
	HandlerType: (*ProvidersServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAll",
			Handler:    _Providers_GetAll_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _Providers_Get_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _Providers_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Providers_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Providers_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "providers.proto",
}
